{% set name = "soxs" %}
{% set version = "4.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/soxs-{{ version }}.tar.gz
  sha256: 52d6f2d8c12b58334418045bcb2d0e61982cbf360abe89f11b738ea4d113bf1e

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - numpy
    - pip
    - cython >=0.29.21
    - setuptools >=45
    - setuptools_scm >=6.2
    - toml
    - wheel >=0.36.2
  run:
    - python
    - astropy >=4.0
    - tqdm
    - pooch
    - h5py >=3.0
    - scipy
    - pyyaml
    - regions
    - appdirs
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - soxs
  commands:
    - pip check
    - get_instrument_data --help
  requires:
    - pip

about:
  home: https://github.com/lynx-x-ray-observatory/soxs/
  summary: Simulated Observations of X-ray Sources
  license: BSD-3-Clause
  license_file: COPYING.txt

extra:
  recipe-maintainers:
    - jzuhone
